name: 'Wreadle'

on:
  repository_dispatch:
    types: [wordle]

jobs:
  wordle:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wreadle
        uses: aryan02420/wreadle@v0.1
        id: wreadle
        with:
          readme: ./README.md
          tag: wreadle
      - name: commit
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am '🐛 Wordle update!' | true
          git push